/**
 * AAOIFI Concept Codes, Rule Constants & System Enums
 * Standard No. 21 (Financial Paper — Shares and Bonds)
 */

export const CONCEPT_CODES = {
  // Rule 3/4/2: Debt (Loans on Interest)
  SHORT_TERM_LOANS_ON_INTEREST: 'SHORT_TERM_LOANS_ON_INTEREST',
  LONG_TERM_LOANS_ON_INTEREST: 'LONG_TERM_LOANS_ON_INTEREST',
  BONDS_DEBENTURES: 'BONDS_DEBENTURES',
  FINANCE_LEASE_LIABILITIES: 'FINANCE_LEASE_LIABILITIES',
  OPERATING_LEASE_LIABILITIES: 'OPERATING_LEASE_LIABILITIES',

  // Rule 3/4/3: Interest-Taking Deposits
  FIXED_DEPOSITS_INTEREST_BEARING: 'FIXED_DEPOSITS_INTEREST_BEARING',
  TREASURY_BILLS: 'TREASURY_BILLS',
  GOVERNMENT_SECURITIES: 'GOVERNMENT_SECURITIES',
  OTHER_INTEREST_BEARING_INVESTMENTS: 'OTHER_INTEREST_BEARING_INVESTMENTS',
  CASH_AND_EQUIVALENTS: 'CASH_AND_EQUIVALENTS',

  // Rule 3/4/4: Prohibited Income
  INTEREST_INCOME: 'INTEREST_INCOME',
  PROHIBITED_INCOME_OTHER: 'PROHIBITED_INCOME_OTHER',
  TOTAL_REVENUE: 'TOTAL_REVENUE',
  OTHER_INCOME: 'OTHER_INCOME',
  TOTAL_INCOME: 'TOTAL_INCOME',

  // Rule 3/4/6: Purification
  SHARES_OUTSTANDING: 'SHARES_OUTSTANDING',

  // Accounting Equation & Validation
  TOTAL_ASSETS: 'TOTAL_ASSETS',
  TOTAL_LIABILITIES: 'TOTAL_LIABILITIES',
  TOTAL_EQUITY: 'TOTAL_EQUITY',
  TOTAL_CURRENT_ASSETS: 'TOTAL_CURRENT_ASSETS',
  TOTAL_NON_CURRENT_ASSETS: 'TOTAL_NON_CURRENT_ASSETS',
  TOTAL_CURRENT_LIABILITIES: 'TOTAL_CURRENT_LIABILITIES',
  TOTAL_NON_CURRENT_LIABILITIES: 'TOTAL_NON_CURRENT_LIABILITIES',
  SHARE_CAPITAL: 'SHARE_CAPITAL',
  SHARE_PREMIUM: 'SHARE_PREMIUM',
  RETAINED_EARNINGS: 'RETAINED_EARNINGS',
  PROPERTY_PLANT_EQUIPMENT: 'PROPERTY_PLANT_EQUIPMENT',
  INVENTORIES: 'INVENTORIES',
  TRADE_RECEIVABLES: 'TRADE_RECEIVABLES',
  TRADE_PAYABLES: 'TRADE_PAYABLES',
  NET_PROFIT: 'NET_PROFIT',
  PROFIT_BEFORE_TAX: 'PROFIT_BEFORE_TAX',
  TAX_EXPENSE: 'TAX_EXPENSE',
  OTHER_NON_SCREENING_ITEM: 'OTHER_NON_SCREENING_ITEM',
};

export const AAOIFI_THRESHOLDS = {
  DEBT_MAX_PERCENT: 30.0,      // Rule 3/4/2: Loans on interest <= 30.0% of Market Cap
  DEPOSITS_MAX_PERCENT: 30.0,  // Rule 3/4/3: Interest-taking deposits <= 30.0% of Market Cap
  PROHIBITED_INCOME_MAX_PERCENT: 5.0, // Rule 3/4/4: Prohibited income <= 5.0% of Total Income
};

export const REPORT_TYPES = {
  ANNUAL: 'ANNUAL',
  QUARTERLY: 'QUARTERLY',
};

export const PERIOD_TYPES = {
  ANNUAL: 'ANNUAL',
  Q1: 'Q1',
  Q2: 'Q2',
  Q3: 'Q3',
  H1: 'H1',
};

export const STATEMENT_TYPES = {
  BALANCE_SHEET: 'BALANCE_SHEET',
  INCOME_STATEMENT: 'INCOME_STATEMENT',
  CASH_FLOW: 'CASH_FLOW',
  NOTES: 'NOTES',
  OTHER: 'OTHER',
};

export const COMPLIANCE_STATUS = {
  COMPLIANT: 'COMPLIANT',
  NON_COMPLIANT: 'NON_COMPLIANT',
  INSUFFICIENT_DATA: 'INSUFFICIENT_DATA',
};

export const MARKET_CAP_VIEWS = {
  PERIOD_DATE: 'PERIOD_DATE',
  SCREENING_DATE: 'SCREENING_DATE',
  AVERAGE_12M: 'AVERAGE_12M',
};

export const SCREENING_VIEWS = {
  STRICT_AAOIFI: 'STRICT_AAOIFI',
  CONSERVATIVE: 'CONSERVATIVE',
};
